name: Pull Request Build
# For pull requests: builds and test
on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master
      - reactive-streams-branch
      - '**'
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          check-latest: true
      - name: build and test
        run: ./gradlew assemble && ./gradlew check --info --stacktrace
        env:
          CI: true
